# Generated by Django 4.2.13 on 2024-06-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coffee",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
