# Generated by Django 4.2.13 on 2024-06-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_coffee_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coffee", name="image", field=models.CharField(max_length=10000),
        ),
    ]
