# Generated by Django 4.2.13 on 2024-06-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_coffee_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("stt", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("image", models.CharField(max_length=10000)),
                ("price", models.FloatField()),
                ("quantity", models.IntegerField()),
                ("Total", models.FloatField()),
            ],
        ),
    ]
