# Generated by Django 4.2.13 on 2024-06-03 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_rename_total_order_total_remove_order_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="completed",),
    ]
