# Generated by Django 4.2.13 on 2024-06-03 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_remove_order_completed"),
    ]

    operations = [
        migrations.RemoveField(model_name="coffee", name="quantity",),
    ]
