# Generated by Django 4.2.13 on 2024-06-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_remove_coffee_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffee", name="quantity", field=models.IntegerField(default=0),
        ),
    ]
