# Generated by Django 4.2.13 on 2024-06-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_alter_coffee_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coffee", name="quantity", field=models.IntegerField(null=True),
        ),
    ]
